version: '3.7'

services:

  mongo:
    image: mongo

    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

    networks:
      - be-upp

    ports:
      - ${MONGO_PORT}:${MONGO_PORT}

    volumes:
      - be_upp_db_mongo:/data/db

  mongo-express:
    image: mongo-express

    restart: unless-stopped

    ports:
      - ${ME_CONFIG_PORT}:${ME_CONFIG_PORT}

    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
      ME_CONFIG_MONGODB_PORT: ${MONGO_PORT}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
      ME_CONFIG_MONGODB_SERVER: ${ME_CONFIG_MONGODB_SERVER}

    depends_on:
      - mongo

    networks:
      - be-upp

  api:
    build:
      context: .

    image: be-upp-dev/api

    container_name: be-upp-dev-api

    volumes:
      - .:/app
      - /app/node_modules

    ports:
      - ${API_PORT}:${API_PORT}

    environment:
      API_PORT: ${API_PORT}
      REACT_APP_API_DOMAIN: ${REACT_APP_API_DOMAIN}
      MONGO_PORT: ${MONGO_PORT}

    command: ./entrypoint.sh

    networks:
      - be-upp

    depends_on:
      - mongo

volumes:
  be_upp_db_mongo:

networks:
  be-upp:
    driver: bridge