# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    
    environment:
      MONGO_INITDB_DATABASE: mongo
      MONGO_INITDB_ROOT_USERNAME: backend
      MONGO_INITDB_ROOT_PASSWORD: beeUpPass
    
    networks:
      - mongo
    
    ports:
      - 27017:27017

    volumes:
      - db_dev_mongo:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: beeUp
      ME_CONFIG_BASICAUTH_PASSWORD: beeUpPass
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: backend
      ME_CONFIG_MONGODB_ADMINPASSWORD: beeUpPass
      ME_CONFIG_MONGODB_SERVER: mongo
    networks:
      - mongo

volumes:
  db_dev_mongo:

networks:
  mongo: