GET http://localhost:9090/open-api/doctor/appointments/
Content-Type: application/json

{
"id": "619edf073106003b50d2db30"
}

###

POST http://localhost:9090/open-api/patient/
Content-Type: application/json

{
"name": "Marc Sion",
"email": "maciolin@mail.com",
"cpf": "81223346596",
"cellphone": "11945158787",
"birth": "1005530400000",
"password": "senhasegura"
}

###

POST http://localhost:9090/open-api/appointment/
Content-Type: application/json

{
    "date": 10,
    "patientId": "619edd7a3106003b50d2db23",
    "doctorId": "619edf073106003b50d2db30"
}

###

POST http://localhost:9090/open-api/doctor/
Content-Type: application/json

{
    "name": "Doutora",
    "email": "doutora@medi.co",
    "password": "medicina123",
    "cellphone": "11945150709",
    "phone": "1135154909",
    "rcn": "22459"
}