POST http://localhost:9090/open-api/doctor/
Content-Type: application/json

{
    "name": "Doutor",
    "email": "doutor@medi.co",
    "password": "medicina123"
}

###

POST http://localhost:9090/open-api/patient/
Content-Type: application/json

{
    "name": "Marcos Siolin",
    "email": "marcossiolin@mail.com",
    "cpf": "11223344556",
    "cellphone": "11945158787",
    "birth": "1005530400000",
    "password": "senhasegura"
}

###

POST http://localhost:9090/open-api/doctor/login/
Content-Type: application/json

{
    "email": "doutor@medi.co",
    "password": "medicina123"
}

###
POST http://localhost:9090/open-api/appointment/
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOWMzY2U2MjQ2MTZjNGY4Y2IxZThkMSIsInByb2ZpbGUiOiJkb2N0b3IiLCJpYXQiOjE2Mzc3MTc3MzcsImV4cCI6MTYzNzgwNDEzN30.S-dD6My34s7Uo629WJhwI8EmjPeMArGTyesWdc0OMBM
Content-Type: application/json

{
    "date": 6,
    "patientId": "619d909e83879d4b944b25c9",
    "doctorId": "619c3ce624616c4f8cb1e8d1"
}